### PR TITLE
Use UITableViewAutomaticDimension instead of hardcoded height value

### PR DESCRIPTION
**Pull request by nataliq**
Using a hardcoded value causes a crash on iOS 9 (trying to find an example that reproduces it) when the header/footer size changes during table view update.

I'm sure there is a reason why 32 was used but we missed to add a comment to it.. does anyone know why it was used? 

We need to test well the example apps to check that this doesn't affect their headers and hopefully find an example that causes the crash.

### CODE REVIEW

**Comment by mansbernhardt** [comment]
@nataliq The magic 32 for sure look strange. Not sure why it was chosen, but I seem to remember that the automatic behavior and resulting header/footer heights etc. behaves quite different between iOS releases and was tricky to get consistent. So I would suggest running the Demo sample on different iOS versions to see that it behaviors consistently. @fennecos has also been involved a lot in getting this work correctly, so perhaps he has some good input.

**Comment by fennecos** [comment]
This `32` was introduced in a commit saying: 
`When we updated TableKit to always return header and footers even if none to create the spacing between section, it broke the automatic height calculations on older devices.`
Not sure why 32, I guess it's the standard height for headers

**Comment by mansbernhardt** [comment]
@fennecos Yes it makes sense that 32 probably is the standard height. We need to test this for both plain and grouped table views and different iOS versions. The Demo sample should provide both plain and grouped versions with two different default stylings.

**Comment by nataliq** [comment]
Ok, since this is causing a crash and the automatic behaviour seem to fix it without obvious breakages we will test with different iOS versions and devices and evaluate if there is a case where headers look broken.

**Comment by nataliq** [comment]
We were not able to find any problems while testing this manually on different iOS versions and the crash on iOS 9 is gone, so I\m merging this.

**Pull request merged**
