### PR TITLE
Add 'shouldResetOnInsertion' to ValueField

### PR DESCRIPTION
**Pull request by achernenko-pp**
### What has been done?

This PR adds a new API to `ValueField`: `shouldResetBeforeNextInsert`.

It works similarly to [`UITextField.clearOnInsertion`](https://developer.apple.com/documentation/uikit/uitextfield/1619631-clearsoninsertion):

> The default value of this property is false. When the value of this property is true and the text field is in editing mode, the selection UI is hidden and inserting new text clears the contents of the text field and sets the value of this property back to false.

`shouldResetBeforeNextInsertion` works both when typing and pasting text.

This API relies on 2 new `TextEditor` properties:
- `isValidCharacter(_:Character)` is needed to make sure that `shouldResetBeforeNextInsertion` disregards the text that could never have been accepted by the field's text editor.
-  `reset()` does the resetting:
    - `NumberEditor` is reset to 0.
    - `ValueEditor<Value>` is reset to the initial value (the `value` parameter passed to the initializer) because this editor generic and there is no single "zero" value that would work for every `Value` type. We could constrain the type to a protocol that requires the conforming types to specify the "zero" value, but that would be a backwards incompatible change requiring a major release. On a second thought, adding a new requirement to the `TextEditor` protocol is not backward compatible either, so maybe we can do it anyway.

### CODE REVIEW

**Comment by nataliq-pp** [comment]
Hey Andrii, looks like a nice addition to ValueField. What's the reasoning behind not calling it `clearOnInsertion` as the behaviour it mimics? I think that will make it easier to find in the future if I'm someone needs it.

Looking at ValueField, looks like it seems to be concerned with the UI appearance of the component and it's just bridging the UI input and interactions to its editor. That being said, wouldn't it make more sense for `TextEditor` to implement this `clearOnInsertion` property? That way `isValidCharacter` doesn't need to be exposed and ValueField doesn't have to be concerned with it. And the protocol property can be implemented to be  backwards compatible with a default value `false`. 

It's very possible that I'm missing something you already explored so please let me know if my suggestion above is not feasible or if you think semantically `TextEditor` is not the right place to have this behaviour.

**Comment by achernenko-pp** [comment]
> What's the reasoning behind not calling it clearOnInsertion as the behaviour it mimics?

There are a two reasons: 
- we don't _clear_ the field per se, clearing would mean that it's empty, while reset returns the field value to a certain state. This becomes especially apparent with `ValueEditor<Value>` which can be configured in a way that prevents it from becoming empty (using the `minCharacters` property).
- the name was given in the Objective-C era. Objective-C had different conventions for naming boolean properties, so I figured I would name this in a more "swifty" way.

**Comment by achernenko-pp** [comment]
I renamed the property to `shouldResetOnInsertion` and moved the logic to `NumberEditor` and `ValueEditor` (as Nataliya said, `ValueField` is responsible for setting up the UI around editors and forwarding the input to them). `ValueField` now relies on its `editor` for the implementation.

**Comment by nataliq-pp** [comment]
It's me again. Since this is a major bump we should clean up the deprecated methods from 2.x

**Comment by achernenko-pp** [comment]
I have cleaned up the warnings and removed the symbols deprecated in 2.x.

> One small thought: as we briefly discussed, the approach suggested in this comment looks more flexible - defaultValue being () -> Value instead of Value. Do you think there can be a case where the default value needs to be computed based on some parameters?

I read the discussion you are referring to. The notion of the default value may be different for different editors with the same `Value`, but I think it's unlikely for it to change at runtime based on some external circumstances, so there isn't much value in making `defaultValue` a function. Let's keep things simple 🙂

**Comment by nataliq-pp** [comment]
👍 I reviewed the last changes, looks good!

**Pull request merged**
