### PR TITLE
Add Minimal Swift Package Manager Example Project

### PR DESCRIPTION
**Pull request by enhorn**
Adds a minimal "Hello Form" project with Form as a Swift package dependency.
The actual file that confirms that Form can be imported and used: [ViewController.swift](https://github.com/iZettle/Form/blob/2dfd71e1aa29e32adaacb16578d940ef6565d48e/Examples/SwiftPackageManager/Example/ViewController.swift)

Skärmavbild 2019-12-18 kl  11 14 48

### CODE REVIEW

**Comment by enhorn** [comment]
Made this WIP, as I need to fix some stuff for CI as well.

**Comment by niil-ohlin** [comment]
Should we really check in the generated Xcode project?

**Comment by enhorn** [comment]
@niil-ohlin Ah, you mean the Workspace? True, it's not included in the other tho example project. I'll remove it.

**Comment by nataliq** [comment]
@enhorn is this one ready for review? There are some pod files still included.

**Comment by enhorn** [comment]
@nataliq Oh yeah. We waited with merging this due to some release I think.
Perhaps @niil-ohlin, @PhilippOtto89 or @moglistree remember if there's some other reason?

**Pull request merged**
